apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  releaseName: cert-manager
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
      version: "v1.5.0"
  interval: 10m0s
  install:
    remediation:
      retries: 3
  values:
    installCRDs: true
    podLabels:
      sidecar.istio.io/inject: 'false'
    cainjector:
      podAnnotations:
        sidecar.istio.io/inject: 'false'
    webhook:
      podAnnotations:
        sidecar.istio.io/inject: 'false'
    startupapicheck:
      jobAnnotations:
        sidecar.istio.io/inject: 'false'
