apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  releaseName: metallb
  chart:
    spec:
      chart: metallb
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
  interval: 10m0s
  install:
    remediation:
      retries: 3
  values:
    controller:
      nodeSelector: { node.kubernetes.io/controller: "true" }
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/controller
          operator: Exists
    configInline:
      peers:
      - peer-address: 192.168.0.151
        peer-asn: 65530
        my-asn: 64500
      address-pools:
      - name: default
        protocol: bgp
        addresses:
          - 192.168.99.1-192.168.99.100
