apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    name: images-garbage-cleaner
  name: images-garbage-cleaner
spec:
  selector:
    matchLabels:
      app: images-garbage-cleaner
  template:
    metadata:
      labels:
        app: images-garbage-cleaner
    spec:
      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
      containers:
        - image: kumargaurav522/docker_cleanup:latest
          name: images-garbage-cleaner
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /var/run/docker.sock
              name: docker-sock
              readOnly: false
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
        - operator: Exists
          effect: NoSchedule
        - key: CriticalAddonsOnly
          operator: Exists
        - operator: Exists
          effect: NoExecute
