---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault-secrets-operator
  namespace: vault
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://ricoberger.github.io/helm-charts
      chart: vault-secrets-operator
      version: 1.16.2
      sourceRef:
        kind: HelmRepository
        name: ricoberger-charts
        namespace: flux-system
      interval: 5m
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    replicaCount: 1
    deploymentStrategy:
      type: Recreate
    image:
      volumeMounts:
        - name: ca
          mountPath: "/etc/vault-secrets-operator"
    volumes:
      - name: ca
        secret:
        secretName: vault-tls
        items:
          - key: ca.crt
            path: ca.crt
    environmentVars:
      - name: VAULT_CACERT
        value: "/etc/vault-secrets-operator/ca.crt"
    vault:
      address: "https://vault:8200"
      authMethod: kubernetes
      kubernetesPath: auth/kubernetes
      kubernetesRole: vault-secrets-operator
      reconciliationTime: "300"
