apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: glusterfs-client
  namespace: kube-system
spec:
  releaseName: glusterfs-client
  chart:
    spec:
      # renovate: registryUrl=https://olli-ai.github.io/helm-charts
      chart: glusterfs-client-provisioner
      version: 1.0.2
      sourceRef:
        kind: HelmRepository
        name: olli-ai
        namespace: flux-system
  interval: 10m0s
  install:
    remediation:
      retries: 3
  values:
    glusterfs:
      server:
        - 192.168.250.11
        - 192.168.250.12
        - 192.168.250.13
        - 192.168.250.14
        - 192.168.250.15
        - 192.168.250.16
      volume: gv0
      path: /kubedata
    storageClass:
      defaultClass: true
    tolerations:
      - key: node-role.kubernetes.io/controller
        effect: NoSchedule
    nodeSelector:
      node.kubernetes.io/controller: "true"
