apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault-operator
  namespace: vault-operator
spec:
  chart:
    spec:
      chart: vault-operator
      sourceRef:
        kind: HelmRepository
        name: banzaicloud
        namespace: flux-system
  interval: 10m0s
  timeout: 5m
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: vault-operator-values
