---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openldap
  namespace: apps
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://jp-gouin.github.io/helm-openldap/
      chart: openldap-stack-ha
      version: 3.0.2
      sourceRef:
        kind: HelmRepository
        name: openldap
        namespace: flux-system
      interval: 5m
  valuesFrom:
    - kind: ConfigMap
      name: ldap-values
    - kind: Secret
      name: ldap-helm-values
      valuesKey: ldap-helm-values
