apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kyverno
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./namespaces/kyverno/kyverno
  prune: true
  wait: true

#---
#apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
#kind: Kustomization
#metadata:
#  name: kyverno-policies
#  namespace: flux-system
#spec:
#  dependsOn:
#    - name: kyverno
#  interval: 5m
#  sourceRef:
#    kind: GitRepository
#    name: flux-system
#  path: ./infra/kyverno/policies
#  prune: true
