apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubed
  namespace: kube-system
spec:
  releaseName: kubed
  chart:
    spec:
      chart: kubed
      sourceRef:
        kind: HelmRepository
        name: appscode
        namespace: flux-system
  interval: 10m0s
  install:
    remediation:
      retries: 3
  values:
    enable-analytics: false
