apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: glusterfs-client
  namespace: kube-system
spec:
  releaseName: glusterfs-client
  chart:
    spec:
      chart: glusterfs-client-provisioner
      sourceRef:
        kind: HelmRepository
        name: olli-ai
        namespace: flux-system
  interval: 10m0s
  install:
    remediation:
      retries: 3
  values:
    glusterfs:
      server:
        - 192.168.250.11
        - 192.168.250.12
        - 192.168.250.13
        - 192.168.250.14
        - 192.168.250.15
        - 192.168.250.16
      volume: gv0
      path: /kubedata
    storageClass:
      defaultClass: true
    nodeSelector: { kubernetes.io/os: "linux" }
