apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: istio-operator
  namespace: flux-system
spec:
  timeout: 5m0s
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./namespaces/istio/operator
  prune: true
  force: true
  validation: client
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: istio-operator
      namespace: istio-operator

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: istio-system
  namespace: flux-system
spec:
  dependsOn:
    - name: istio-operator
  timeout: 5m0s
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./namespaces/istio/system
  prune: true
  force: true
  validation: client
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: istiod
      namespace: istio-system
    - apiVersion: apps/v1
      kind: Deployment
      name: prometheus
      namespace: istio-system
    - apiVersion: apps/v1
      kind: Deployment
      name: jaeger
      namespace: istio-system
    - apiVersion: apps/v1
      kind: Deployment
      name: grafana
      namespace: istio-system
    - apiVersion: apps/v1
      kind: Deployment
      name: kiali
      namespace: istio-system
    - apiVersion: apps/v1
      kind: Deployment
      name: flagger
      namespace: istio-system

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: istio-gateway
  namespace: flux-system
spec:
  dependsOn:
    - name: istio-system
  timeout: 5m0s
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./namespaces/istio/gateway
  prune: true
  force: true
  validation: client
