---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: metrics-server
      version: 0.5.1
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: flux-system
      interval: 5m
