---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: metrics-server
      version: 3.6.0
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: flux-system
      interval: 5m
  values:
    defaultArgs:
      - --cert-dir=/tmp
      - --kubelet-preferred-address-types=Hostname
      - --kubelet-insecure-tls
      - --kubelet-use-node-status-port
      - --metric-resolution=15s
