---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
#  - release.yaml
#  - hpa.yaml
configMapGenerator:
  - name: podinfo-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml

