service:
  enabled: true
  type: ClusterIP
  metricsPort: 9797
  httpPort: 9898
ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: le-nginx
    ingress.kubernetes.io/ssl-passthrough: "false"
    kubernetes.io/load-balance: ip_hash
    nginx.ingress.kubernetes.io/service-upstream: "true"
    nginx.ingress.kubernetes.io/upstream-vhost: podinfo.apps.svc.cluster.local
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
      SecRuleEngine On
    nginx.ingress.kubernetes.io/server-snippet: |
      proxy_ssl_name pod-info.ingress.space;
      proxy_ssl_server_name on;
#    nginx.ingress.kubernetes.io/auth-response-headers: Authorization
#    nginx.ingress.kubernetes.io/auth-signin: https://auth.ingress.space/oauth2/start?rd=$escaped_request_uri
#    nginx.ingress.kubernetes.io/auth-url: https://auth.ingress.space/oauth2/auth
#    nginx.ingress.kubernetes.io/configuration-snippet: |
#      auth_request_set $name_upstream_1 $upstream_cookie_name_1;
#
#      access_by_lua_block {
#        if ngx.var.name_upstream_1 ~= "" then
#          ngx.header["Set-Cookie"] = "name_1=" .. ngx.var.name_upstream_1 .. ngx.var.auth_cookie:match("(; .*)")
#        end
#      }

  hosts:
    - host: pod-info.ingress.space
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: pod-info-cert
      hosts:
        - pod-info.ingress.space
