service:
  enabled: true
  type: ClusterIP
  metricsPort: 9797
  httpPort: 9898
ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: le-nginx
    ingress.kubernetes.io/ssl-passthrough: "false"
    kubernetes.io/ingress.class: nginx
    kubernetes.io/load-balance: ip_hash
    nginx.ingress.kubernetes.io/service-upstream: "true"
    nginx.ingress.kubernetes.io/upstream-vhost: podinfo.apps.svc.cluster.local
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
      SecRuleEngine On
    nginx.ingress.kubernetes.io/server-snippet: |
      proxy_ssl_name podinfo.ingress.space;
      proxy_ssl_server_name on;
  hosts:
    - host: podinfo.ingress.space
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: podinfo-cert
      hosts:
        - podinfo.ingress.space
