apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: apps
spec:
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  interval: 10m0s
  timeout: 5m
  install:
    remediation:
      retries: 3
  values:
    controller:
      image:
        allowPrivilegeEscalation: false
      scope:
        enabled: true
        namespace: "apps"
      podLabels:
        sidecar.istio.io/inject: 'true'
      podAnnotations:
        prometheus.io/port: '10254'
        prometheus.io/scrape: 'true'
        traffic.sidecar.istio.io/includeInboundPorts: ''
        traffic.sidecar.istio.io/excludeInboundPorts: '80,443'
        traffic.sidecar.istio.io/excludeOutboundIPRanges: 10.3.0.1/32
      autoscaling:
        enabled: true
      config:
        enable-modsecurity: true
        enable-owasp-modsecurity: true
      resources:
        requests:
          cpu: 500m
          memory: 500Mi
      admissionWebhooks:
        patch:
          podAnnotations:
            sidecar.istio.io/inject: 'false'
          labels:
            sidecar.istio.io/inject: 'false'
