controller:
  image:
    allowPrivilegeEscalation: false
  scope:
    enabled: true
    namespace: "apps"
  podLabels:
    sidecar.istio.io/inject: 'true'
  podAnnotations:
    prometheus.io/port: '10254'
    prometheus.io/scrape: 'true'
    traffic.sidecar.istio.io/includeInboundPorts: ''
    traffic.sidecar.istio.io/excludeInboundPorts: '80,443'
    traffic.sidecar.istio.io/excludeOutboundIPRanges: 10.3.0.1/32
  autoscaling:
    enabled: true
  config:
    enable-modsecurity: "true"
    enable-owasp-modsecurity-crs: "true"
    modsecurity-snippet: |
      SecRuleEngine On
      SecRequestBodyAccess On
      SecAuditEngine RelevantOnly
      SecAuditLogType Serial
      SecAuditLogParts ABIJDEFHZ
      SecAuditLog /dev/stdout
      SecAuditLogFormat JSON
    server-name-hash-bucket-size: "256"
    server-tokens: "false"
    ssl-ciphers: ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA:AES256-GCM-SHA384:AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256:AES256-SHA:AES128-SHA:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4
    ssl-protocols: TLSv1.1 TLSv1.2
    use-http2: "true"
  resources:
    requests:
      cpu: 500m
      memory: 500Mi
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  metrics:
    enabled: true
  admissionWebhooks:
    patch:
      labels:
        sidecar.istio.io/inject: 'false'
