controller:
  image:
    allowPrivilegeEscalation: false
  scope:
    enabled: true
    namespace: "apps"
  podLabels:
    sidecar.istio.io/inject: 'true'
  podAnnotations:
    prometheus.io/port: '10254'
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
    traffic.sidecar.istio.io/includeInboundPorts: ''
    traffic.sidecar.istio.io/excludeInboundPorts: '80,443'
    traffic.sidecar.istio.io/excludeOutboundIPRanges: 10.3.0.1/32
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 11
    targetMemoryUtilizationPercentage: 0
    behavior:
      scaleDown:
        stabilizationWindowSeconds: 30
        policies:
        - type: Percent
          value: 50
          periodSeconds: 15
      scaleUp:
        stabilizationWindowSeconds: 30
        policies:
        - type: Percent
          value: 50
          periodSeconds: 15
  autoscalingTemplate:
    - type: Pods
      pods:
        metric:
          name: nginx_ingress_controller_nginx_process_requests_per_second
        target:
          type: AverageValue
          averageValue: "20"
  service:
    externalTrafficPolicy: Local
    loadBalancerIP: 192.168.99.2    
  config:
    http-snippet: |
      map $remote_addr $logging {
          default 1;
          ~^192.168.0.*$ 0;
      }
    access-log-params: "main if=$logging"
    server-snippet: |
      ssl_session_cache shared:SSL:10m;
      ssl_stapling on;
      ssl_stapling_verify on;
      add_header X-Frame-Options DENY;
      add_header X-XSS-Protection "1; mode=block";
    modsecurity-snippet: |
      SecRuleEngine On
      Include /etc/nginx/owasp-modsecurity-crs/nginx-modsecurity.conf
      SecRequestBodyAccess On
      SecAuditEngine RelevantOnly
      SecAuditLogType Serial
      SecAuditLogParts ABIJDEFHZ
      SecAuditLog /dev/stdout
      SecAuditLogFormat JSON
    enable-modsecurity: "true"
#    enable-owasp-modsecurity-crs: "true"
    client-body-buffer-size: "10K"
    server-name-hash-bucket-size: "256"
    server-tokens: "false"
    ssl-ciphers: EECDH+AESGCM:EDH+AESGCM
    ssl-ecdh-curve: secp384r1
    ssl-prefer-server-ciphers: "true"
    ssl-protocols: TLSv1.2 TLSv1.3
    ssl-session-timeout: 10m
    ssl-session-tickets: "false"
    enable-brotli: "true"
    global-rate-limit-memcached-host: memcached
  resources:
    requests:
      cpu: 500m
      memory: 500Mi
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  metrics:
    enabled: true
  admissionWebhooks:
    patch:
      labels:
        sidecar.istio.io/inject: 'false'
