apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: glusterfs-client
  namespace: kube-system
spec:
  releaseName: glusterfs-client
  chart:
    spec:
      # renovate: registryUrl=https://olli-ai.github.io/helm-charts
      chart: glusterfs-client-provisioner
      version: 1.0.2
      sourceRef:
        kind: HelmRepository
        name: olli-ai
        namespace: flux-system
  interval: 10m0s
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: glusterfs-values
