apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo2
spec:
  releaseName: podinfo2
  chart:
    spec:
      chart: podinfo
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: flux-system
      version: ">=1.0.0-alpha"
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    service:
      enabled: true
      type: ClusterIP
      metricsPort: 9797
      httpPort: 9898
