---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  timeout: 5m0s
  interval: 10m0s
  dependsOn:
    - name: istio-system
  path: "./infra/cert-manager/controller"
  prune: true
  validation: client
  targetNamespace: apps
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: cert-manager
      namespace: apps
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: letsencrypt
  namespace: flux-system
spec:
  interval: 10m
  timeout: 5m
  dependsOn:
    - name: cert-manager
  path: "./infra/cert-manager/crd"
  prune: true
  validation: client
  targetNamespace: apps
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
