---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  dependsOn:
    - name: istio-system
  interval: 5m
  path: "./infra/cert-manager/controller"
  prune: true
  targetNamespace: istio-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: cert-manager
      namespace: istio-system

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: letsencrypt
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-manager
  interval: 5m
  path: "./infra/cert-manager/crd"
  prune: true
  targetNamespace: istio-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
