---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
resources:
  - release.yaml
  - oauth2-config-secret.yaml
configMapGenerator:
  - name: oauth2-proxy-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml

