---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: oauth2-proxy
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://oauth2-proxy.github.io/manifests
      chart: oauth2-proxy
      version: 6.23.1
      sourceRef:
        kind: HelmRepository
        name: oauth2-proxy-charts
        namespace: flux-system
      interval: 5m
  valuesFrom:
  - kind: ConfigMap
    name: oauth2-proxy-values
  - kind: Secret
    name: oauth2-proxy-secret
    valuesKey: config
    optional: false
