image:
  repository: "quay.io/oauth2-proxy/oauth2-proxy"
  tag: "v7.2.1"
replicaCount: 2
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: le-nginx
    ingress.kubernetes.io/ssl-passthrough: "false"
    kubernetes.io/load-balance: ip_hash
    nginx.ingress.kubernetes.io/service-upstream: "true"
    nginx.ingress.kubernetes.io/upstream-vhost: oauth2-proxy.apps.svc.cluster.local
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
      SecRuleEngine On
    nginx.ingress.kubernetes.io/server-snippet: |
      proxy_ssl_name auth.ingress.space;
      proxy_ssl_server_name on;    
  path: /oauth2
  hosts: [auth.ingress.space]
  tls:
  - secretName: auth-ingress-space-cert
    hosts:
      - auth.ingress.space
extraArgs:
  provider: oidc
  oidc-issuer-url: https://linuxology.eu.auth0.com/
  redirect-url: https://auth.ingress.space/oauth2/callback
  skip-provider-button:
  pass-authorization-header:
  set-xauthrequest: "true"
  pass-access-token: "true"
  email-domain: "*"
  cookie-domain: .ingress.space
  whitelist-domain: .ingress.space .apps.svc.cluster.local
affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchExpressions:
        - key: app.kubernetes.io/name
          operator: In
          values:
          - oauth2-proxy
      topologyKey: "kubernetes.io/hostname"
