image:
  repository: "quay.io/oauth2-proxy/oauth2-proxy"
  tag: "v7.2.0"
replicaCount: 2
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  path: /oauth2
  hosts: [auth.ingress.space]
  tls:
  - hosts:
    - auth.ingress.space
extraArgs:
  provider: oidc
  oidc-issuer-url: https://linuxology.eu.auth0.com/
  skip-provider-button:
  pass-authorization-header:
  email-domain: "*"
  cookie-domain: .ingress.space
  whitelist-domain: .ingress.space
affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchExpressions:
        - key: app.kubernetes.io/name
          operator: In
          values:
          - oauth2-proxy
      topologyKey: "kubernetes.io/hostname"
