---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: authentik
resources:
  - authentik-config-secret.yaml
  - release.yaml
  - namespace.yaml
configMapGenerator:
  - name: authentik-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml

