apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: descheduler
  namespace: kube-system
spec:
  releaseName: descheduler
  chart:
    spec:
      chart: descheduler
      sourceRef:
        kind: HelmRepository
        name: descheduler
        namespace: flux-system
  interval: 10m0s
  install:
    remediation:
      retries: 3
  values:
    kind: Deployment
    tolerations:
      - key: node-role.kubernetes.io/controller
        effect: NoSchedule
    nodeSelector:
      node.kubernetes.io/controller: "true"
