apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: test-ingressgateway
  namespace: istio-test
spec:
  selector:
    istio: istio-ingressgateway-test
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"