---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
resources:
  - authelia-helm-vaules.yaml
  - release.yaml
#  - istio_vs.yaml
configMapGenerator:
  - name: authelia-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml

