apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-system
spec:
  releaseName: ingress-nginx
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  interval: 10m0s
  install:
    remediation:
      retries: 3
  values:
    controller:
      labels:
        sidecar.istio.io/inject: 'true'
      podAnnotations:
        traffic.sidecar.istio.io/includeInboundPorts: ''
        traffic.sidecar.istio.io/excludeInboundPorts: '80,443'
      autoscaling:
        enabled: true
      config:
        enable-modsecurity: true
        enable-owasp-modsecurity: true
      resources:
        requests:
          cpu: 500m
          memory: 500Mi
