---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.min.io/
      chart: minio
      version: 4.0.2
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: flux-system
      interval: 5m
  valuesFrom:
#  - kind: Secret
#    name: minio-helm-values
#    valueKey: minio-helm-values
#    optional: false
  - kind: ConfigMap
    name: minio-values
