replicas: 6

persistence:
  size: 50Gi
  subPath: "minio"
resources:
  requests:
    memory: 350Mi
    cpu: 25m
  limits:
    memory: 1000Mi
securityContext:
  enabled: false
metrics:
  serviceMonitor:
    enabled: true
nasgateway:
  enabled: true
  # Number of parallel instances
  replicas: 3


tolerations:
  - key: node-role.kubernetes.io/controller
    effect: NoSchedule

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - minio
        topologyKey: kubernetes.io/hostname
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - minio
          topologyKey: failure-domain.beta.kubernetes.io/zone

