apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
spec:
  releaseName: podinfo
  chart:
    spec:
      chart: podinfo
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: flux-system
      version: ">=1.0.0-alpha"
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    service:
      enabled: true
      type: ClusterIP
      metricsPort: 9797
      httpPort: 9898
    ingress:
      enabled: true
      className: istio
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      hosts:
        - host: podinfo.ingress.space
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: podinfo-cert
          hosts:
            - podinfo.ingress.space
