---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home
resources:
  - release.yaml
configMapGenerator:
  - name: pihole-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml

