apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-adapter
  namespace: monitoring
spec:
  releaseName: prometheus-adapter
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://prometheus-community.github.io/helm-charts
      chart: prometheus-adapter
      version: 3.0.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 5m
  values:
    prometheus:
      url: http://prometheus-prometheus.monitoring
      port: 9090
    rules:
      default: false
      custom:
        - seriesQuery: istio_requests_total{destination_workload_namespace!="",kubernetes_pod_name!="",reporter="destination"}
          resources:
            overrides:
              destination_workload_namespace: {resource: "namespace"}
              kubernetes_pod_name: {resource: "pod"}
          name:
            matches: ^(.*)_total
            as: ${1}_per_second
          metricsQuery: sum(rate(<<.Series>>{<<.LabelMatchers>>,reporter="destination"}[2m])) by (<<.GroupBy>>)
