apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: starboard
spec:
  releaseName: starboard
  chart:
    spec:
      # renovate: registryUrl=https://aquasecurity.github.io/helm-charts/
      chart: starboard-operator
      sourceRef:
        kind: HelmRepository
        name: aquasecurity
        namespace: flux-system
      version: "0.7.0"
  interval: 10m0s
  install:
    remediation:
      retries: 3
  values:
    targetNamespaces: ""
    trivy.ignoreUnfixed: true
    installCRDs: true
