apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: vault-operator
  namespace: vault-operator
spec:
  interval: 5m
  path: "./namespaces/vault/operator"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system

#---
#apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
#kind: Kustomization
#metadata:
#  name: crd-vault
#  namespace: vault
#spec:
#  dependsOn:
#    - name: vault-operator
#  interval: 5m
#  path: "./namespaces/vault/crd"
#  prune: true
#  sourceRef:
#    kind: GitRepository
#    name: flux-system
#    namespace: flux-system

