apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: vault-operator
  namespace: vault-operator
spec:
  interval: 5m
  path: "./namespaces/vault/operator"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: crd-vault
  namespace: vault-operator
spec:
  dependsOn:
    - name: vault-operator
  interval: 5m
  path: "./namespaces/vault/crd"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: vault-secrets-operator
  namespace: vault-operator
spec:
  dependsOn:
    - name: crd-vault
  interval: 5m
  path: "./namespaces/vault/vault-secrets-operator"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: vault-secrets
  namespace: vault-operator
spec:
  dependsOn:
    - name: vault-secrets-operator
  interval: 5m
  path: "./namespaces/vault/secrets"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
