image:
  repository: ghcr.io/goauthentik/server
  tag: 2021.12.1

ingress:
  enabled: true
  ingressClassName: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: le-nginx
    ingress.kubernetes.io/ssl-passthrough: "false"
    kubernetes.io/load-balance: ip_hash
    nginx.ingress.kubernetes.io/service-upstream: "true"
    nginx.ingress.kubernetes.io/upstream-vhost: authentik.apps.svc.cluster.local
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
      SecRuleEngine On
      SecRuleRemoveById 949110
    nginx.ingress.kubernetes.io/server-snippet: |
      proxy_ssl_name authentik.ingress.space;
      proxy_ssl_server_name on;
  hosts:
  - host: authentik.ingress.space
    paths:
    - path: /

  tls:
  - secretName: authentik-ingress-space
    hosts:
    - authentik.ingress.space

geoip:
  enabled: false
authentik:
  log_level: debug

  outposts:
    docker_image_base: ghcr.io/goauthentik/%(type)s:%(version)s

  postgresql:
    host: '{{ .Release.Name }}-postgresql'
  redis:
    host: '{{ .Release.Name }}-redis-master'

postgresql:
  enabled: true
  persistence:
    enabled: true

redis:
  enabled: true
