apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
spec:
  releaseName: podinfo
  chart:
    spec:
      # renovate: registryUrl=https://stefanprodan.github.io/podinfo
      chart: podinfo
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: flux-system
      version: ">=1.0.0-alpha"
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    service:
      enabled: true
      type: ClusterIP
      metricsPort: 9797
      httpPort: 9898
    podAnnotations:
      prometheus.io/path: '/metrics'
#      prometheus.io/port: '9797'
#      prometheus.io/scrape: 'true'
