apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-sync-annotation
spec: 
  rules: 
  - name: add-label
    match:
      resources:
        kinds:
        - Secret
        namespaces:
        - apps
    mutate:
      patchStrategicMerge:
        metadata:
          annotations:
            +(kubed.appscode.com/sync): "cert-manager-tls=ingress"
