---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes-sigs.github.io/metrics-server
      chart: metrics-server
      version: 3.8.4
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: flux-system
      interval: 5m
  values:
    defaultArgs:
      - --cert-dir=/tmp
      - --kubelet-preferred-address-types=InternalIP
      - --kubelet-insecure-tls
      - --kubelet-use-node-status-port
      - --metric-resolution=15s
    tolerations:
      - key: node-role.kubernetes.io/controller
        effect: NoSchedule
    nodeSelector:
      node.kubernetes.io/controller: "true"
