apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  releaseName: cert-manager
  chart:
    spec:
      # renovate: registryUrl=https://charts.jetstack.io
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
      version: "v1.5.0"
  interval: 10m0s
  timeout: 5m0s
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      remediateLastFailure: false
  values:
    installCRDs: true
     podAnnotations:
       traffic.sidecar.istio.io/excludeOutboundIPRanges: 10.3.0.1/32
#    podLabels:
#      sidecar.istio.io/inject: 'false'
#    cainjector:
#      podAnnotations:
#        sidecar.istio.io/inject: 'false'
#    webhook:
#      podAnnotations:
#        sidecar.istio.io/inject: 'false'
    startupapicheck:
      podAnnotations:
        sidecar.istio.io/inject: 'false'
