---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authelia-postgres
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: postgresql
      version: 11.9.13
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 5m
  valuesFrom:
    - kind: ConfigMap
      name: postgres-authelia-values
    - kind: Secret
      name: authelia-postgres-helm-values
      valuesKey: authelia-postgres-helm-values
