---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
resources:
  - postfix-helm-vaules.yaml
  - release.yaml
configMapGenerator:
  - name: postfix-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml

