---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postfix
  namespace: apps
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://bokysan.github.io/docker-postfix/
      chart: mail
      version: v3.4.0
      sourceRef:
        kind: HelmRepository
        name: bokysan
        namespace: flux-system
      interval: 5m
  valuesFrom:
    - kind: ConfigMap
      name: postfix-values
    - kind: Secret
      name: postfix-helm-values
      valuesKey: postfix-helm-values
