fullnameOverride: postfix

service:
  port: 25

config:
  general:
    INBOUND_DEBUGGING: "true"
    POSTFIX_mynetworks: "127.0.0.0/8 10.0.0.0/8 172.0.0.0/8 192.168.0.0/16 "
    POSTFIX_smtpd_client_restrictions: "permit_mynetworks"
    POSTFIX_smtp_sasl_security_options: "noanonymous"
    POSTFIX_smtp_tls_loglevel: "1"

