config:
  general:
    INBOUND_DEBUGGING: "true"
    POSTFIX_mynetworks: "0.0.0.0/0"
    POSTFIX_smtpd_client_restrictions: "permit_mynetworks"
    POSTFIX_smtp_sasl_security_options: "noanonymous"
    POSTFIX_smtp_tls_loglevel: "1"
    POSTFIX_inet_interfaces: "0.0.0.0"
