fullnameOverride: prometheus
defaultRules:
  rules:
    kubeApiserverAvailability: true
    kubeApiserver: true

server:
  resources:
    requests:
      memory: 1500Mi
      cpu: 25m
    limits:
      memory: 2000Mi

prometheusOperator:
  createCustomResource: true
  configReloaderCpu: 200m
  admissionWebhooks:
    enabled: true

alertmanager:
  alertmanagerSpec:
    podAntiAffinity: "hard"
  config:
    global:
      resolve_timeout: 5m
    inhibit_rules:
    - source_match:
        severity: 'critical'
      target_match:
        severity: 'warning'
      # Apply inhibition if the alertname is the same.
      equal: ['alertname', 'namespace']
    templates: ["*.tmpl"]
  templateFiles:
    pagerduty-custom.tmpl: |-
      {{- define "pagerduty.custom.description" -}}[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ if ne .CommonAnnotations.summary ""}}{{ .CommonAnnotations.summary }} {{ else if ne .CommonAnnotations.message ""}}{{ .CommonAnnotations.message }} {{ else if ne .CommonAnnotations.description ""}}{{ .CommonAnnotations.description }} {{ else }}{{ .CommonLabels.alertname }}{{ end }}{{- end -}}

nodeExporter:
  serviceMonitor:
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_node_name]
      targetLabel: instance
      action: replace

grafana:
  dashboards:
    default:
      ingress-nginx:
        # Ref: https://grafana.com/dashboards/9614
        gnetId: 9614
        revision: 1
        datasource: Prometheus

prometheus:
  prometheusSpec:
    replicas: 1
    replicaExternalLabelName: "replica"
    ruleSelector: {}
    ruleNamespaceSelector: {}
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelector: {}
    podMonitorNamespaceSelector: {}
    podMonitorSelectorNilUsesHelmValues: false
    retention: 4h
    enableAdminAPI: true
    walCompression: true
    storageSpec:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 20Gi

